name: Apply GitHub Repository Settings

on:
  push:
    branches: [ main ]
    paths:
      - github-settings/**
      - .github/workflows/apply-github-settings.yml

  workflow_dispatch:

permissions:
  contents: read

jobs:
  github-settings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: github-settings
        run: terraform init

      - name: Terraform Import Repo
        run: |
          FULL_REPO="${{ github.repository }}"
          OWNER="${{ github.repository_owner }}"
          REPO_NAME="${FULL_REPO/$OWNER\//}"
          echo $REPO_NAME
          terraform import github_repository.repo $GITHUB_REPOSITORY
        working-directory: github-settings
        env:
          TF_VAR_github_token: ${{ secrets.GH_PAT }}

      - name: Terraform Plan
        working-directory: github-settings
        run: terraform plan -out=tfplan
        env:
          TF_VAR_github_token: ${{ secrets.GH_PAT }}

      - name: Terraform Apply
        working-directory: github-settings
        run: terraform apply "tfplan"
        env:
          TF_VAR_github_token: ${{ secrets.GH_PAT }}